notifications:
  email: false
  
language: shell       # 'language: python' is an error on Travis CI macOS
python: 
  - "3.7"
  
matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
           PLAT=manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
           PLAT=manylinux1_i686
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           PLAT=manylinux2010_x86_64

install:
  - docker pull $DOCKER_IMAGE

script:
  - chmod 777 travis/build-wheels.sh
  - docker run -e PLAT=$PLAT
               -v `pwd`:/io 
               $DOCKER_IMAGE
               /io/travis/build-wheels.sh


