notifications:
  email: false
  
language: python
python: 
  - "3.7"
  
matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
           PLAT=manylinux1_x86_64
           USE_OMP=0
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
           USE_OMP=1
           PLAT=manylinux1_i686
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           USE_OMP=1
           PLAT=manylinux2010_x86_64

install:
  - docker pull $DOCKER_IMAGE
  - pip3 install twine

script:
  # This seems to be have become necessary only recently.
  - chmod 777 travis/build-wheels.sh

  # Run build-wheels.sh within the manylinux docker image
  - docker run -e PLAT=$PLAT        # Pass on docker image name
               -e USE_OMP=$USE_OMP  # Pass on compile with OpenMP
               -v `pwd`:/io         # Alias 'here' with the base path /io to allow files to be exchanged.
               $DOCKER_IMAGE
               /io/travis/build-wheels.sh

  # Upload the wheels placed in the wheels/ folder.
  - twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ wheels/* --non-interactive



